@startmindmap 功能模块
title 大学生兼职/家教平台

* **大学生兼职/家教平台**
** 用户管理
*** 用户注册
*** 身份认证、存档
*** 用户登录
** 发布招聘信息
*** 担保
*** 评价/投诉机制
*** 搜索/筛选
** 发布求职意向
*** 简单简历
*** 搜索/筛选
** 大学生与家长沟通
*** 传统电话联系
*** 在线实时交流
@endmindmap