@startuml 总体业务流程1
title 总体业务流程1
start
:注册账号;
:身份核验;
note left:学生证、身份证、\n本人照片（手持证件）;
note right:为了减轻隐私顾虑，\n可让用户自行加上水印;
fork
    :大学生发布求职意向;
    :家长浏览查找兼职学生;
fork again
    :家长等发布招聘信息;
    :大学生浏览选择合适岗位;
end fork
:双方建立联系;
note left:留言、预留的手机号\n在线（电子邮件或短信通知）
if(合作达成)then(F)
    stop
endif
:家长预付部分担保金;
:提示双方签署正式合同，并拍照留档;
note left:提供标准合同模板
:进入实际教学阶段;
@enduml